"""Add external ID to profile 🛂

Revision ID: a842be825e0c
Revises: 7d6068e835af
Create Date: 2023-11-16 12:57:11.502837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a842be825e0c"
down_revision: Union[str, None] = "7d6068e835af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("external_id", sa.String(), nullable=True)
    )
    op.create_unique_constraint(
        "profiles__external_id__unique", "profiles", ["external_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("profiles__external_id__unique", "profiles", type_="unique")
    op.drop_column("profiles", "external_id")
    # ### end Alembic commands ###
